// <auto-generated />
namespace M17E_Lar.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class medicamentoatt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(medicamentoatt));
        
        string IMigrationMetadata.Id
        {
            get { return "202303141602141_medicamentoatt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
