// <auto-generated />
namespace M17E_Lar.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class jaime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(jaime));
        
        string IMigrationMetadata.Id
        {
            get { return "202303151145510_jaime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
